name: Deploying stg Branch

on:
  push:
    branches:
      - stg

jobs:
  deploy:
    runs-on: [self-hosted, price-vm]

    env:
      CONTAINER_NAME: price-stage-be
      IMAGE_NAME: price-stage-be
      PORT: 3000

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          clean: false

      # Build Docker image
      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME .

      # Stop & remove old container (if exists)
      - name: Stop and Remove Old Container
        run: |
          if [ "$(docker ps -aq -f name=$CONTAINER_NAME)" ]; then
            echo "Stopping existing container..."
            docker stop $CONTAINER_NAME || true
            docker rm $CONTAINER_NAME || true
          fi

      # Run new container
      - name: Run New Container
        run: |
          docker run -d \
            --name $CONTAINER_NAME \
            -p $PORT:$PORT \
            --restart unless-stopped \
            $IMAGE_NAME
